# Numpy

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]

In [5]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [6]:
type(arr)

numpy.ndarray

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [21]:
np.random.randint(0,1000)

549

In [22]:
np.random.randint(0,1000, (2,2))

array([[778, 458],
       [132, 329]])

In [44]:
# defy randomness, seed
np.random.seed(101)
arr = np.random.randint(0,100,100)

In [45]:
print(arr)
print(arr.mean())
print(arr.reshape(10,10))

mat = arr.reshape(10,10)

[95 11 81 70 63 87 75  9 77 40  4 63 40 60 92 64  5 12 93 40 49 83  8 29
 59 34 44 72 19 10 76 95 87  0 73  8 62 36 83 99 28 63  7 10 52 56 38 73
 52 18 71 15 44  0 12 17 75 79 97 93 24 36 63 19 35 30 10 60 20 27  8 86
 26 87 46 47 54 86  9 45  2 18 58 92 11 10 94 35 28  3 83 84 47 14 69 60
 69 51  6 88]
47.47
[[95 11 81 70 63 87 75  9 77 40]
 [ 4 63 40 60 92 64  5 12 93 40]
 [49 83  8 29 59 34 44 72 19 10]
 [76 95 87  0 73  8 62 36 83 99]
 [28 63  7 10 52 56 38 73 52 18]
 [71 15 44  0 12 17 75 79 97 93]
 [24 36 63 19 35 30 10 60 20 27]
 [ 8 86 26 87 46 47 54 86  9 45]
 [ 2 18 58 92 11 10 94 35 28  3]
 [83 84 47 14 69 60 69 51  6 88]]


In [46]:
# access the column
mat[0]

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [47]:
mat[0,:]

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [48]:
mat[:,0]

array([95,  4, 49, 76, 28, 71, 24,  8,  2, 83])

In [51]:
mat[0:3,0:3]

array([[95, 11, 81],
       [ 4, 63, 40],
       [49, 83,  8]])

In [52]:
# boolean masking
mat[mat>50]

array([95, 81, 70, 63, 87, 75, 77, 63, 60, 92, 64, 93, 83, 59, 72, 76, 95,
       87, 73, 62, 83, 99, 63, 52, 56, 73, 52, 71, 75, 79, 97, 93, 63, 60,
       86, 87, 54, 86, 58, 92, 94, 83, 84, 69, 60, 69, 51, 88])