In [1]:
import tensorflow as tf
print(tf.version.VERSION)

2.3.2


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.45242214,  1.1130165 ,  0.23404934,  0.10230789, -0.17066213,
         0.19347382,  0.05147639, -0.32786795,  0.15926018,  0.18383147]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.05190271, 0.2483427 , 0.10311475, 0.09038705, 0.06879499,
        0.09901457, 0.08590736, 0.05878726, 0.09568421, 0.09806442]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.3124883

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2960 - accuracy: 0.9133
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1431 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1072 - accuracy: 0.9668
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0880 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0740 - accuracy: 0.9769


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0768 - accuracy: 0.9763


[0.07680261135101318, 0.9763000011444092]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.1476061e-06, 1.2530542e-08, 1.8580009e-06, 2.4901881e-04,
        1.3163046e-11, 2.6140873e-07, 4.7081040e-13, 9.9967408e-01,
        1.4994902e-07, 7.3524156e-05],
       [1.5814491e-08, 1.5845563e-04, 9.9984002e-01, 7.6497810e-07,
        2.3572474e-15, 1.2050396e-07, 1.7996456e-07, 2.8214630e-13,
        3.8809040e-07, 5.2308501e-11],
       [1.3108576e-07, 9.9959379e-01, 2.4381567e-05, 7.9361666e-07,
        5.2467021e-05, 5.9374105e-07, 4.7249509e-06, 2.5433765e-04,
        6.6309360e-05, 2.4669664e-06],
       [9.9986255e-01, 1.1458007e-09, 9.4876923e-05, 1.8778251e-06,
        1.5764546e-07, 1.9614702e-06, 1.6199394e-05, 9.7491611e-06,
        4.3826503e-07, 1.2223524e-05],
       [2.1821765e-05, 6.4499955e-10, 3.3922692e-07, 4.5260133e-09,
        9.9901283e-01, 4.2249429e-08, 2.1929675e-06, 3.0000749e-05,
        9.0835997e-08, 9.3271671e-04]], dtype=float32)>